core/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from core import views

urlpatterns = [
    path("test/", views.test, name="test"),
    path("", views.dashboard, name="dashboard"),
    path("employees/list/", views.employee_list, name="employee_list"),
    path("employees/detail/<int:pk>/", views.employee_detail, name="employee_detail"),
    path(
        "employees/create/",
        login_required(views.CreateEmployeeView.as_view()),
        name="employee_create",
    ),
    path(
        "employees/update/<int:pk>/",
        login_required(views.UpdateEmployeeView.as_view()),
        name="employee_update",
    ),
    path(
        "employees/attendance/<int:pk>/",
        views.list_employee_attendances,
        name="employee_attendance",
    ),
    path(
        "employees/billing/<int:pk>/",
        views.view_employee_billing,
        name="employee_billing",
    ),
    path("attendance/", views.attendance, name="attendance"),
    path(
        "attendance/<int:attn_id>/update/",
        views.update_attendance,
        name="update_attendance",
    ),
    path(
        "attendance/<int:attn_id>/delete/",
        views.delete_attendance,
        name="delete_attendance",
    ),
]

presentpay/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
]

core/models.py
import datetime

from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField

from accounts.models import Company


class Department(models.Model):
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=255, blank=True, null=True, default="")

    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Employee(models.Model):
    GENDER_CHOICES = (("M", "Male"), ("F", "Female"), ("O", "Other"))

    first_name = models.CharField(max_length=64)
    middle_name = models.CharField(max_length=64, blank=True, default="")
    last_name = models.CharField(max_length=64, blank=True, default="")
    phone = PhoneNumberField(blank=False, null=False)
    email = models.EmailField(blank=True, null=True)
    role = models.CharField(max_length=128, blank=True, default="")
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    joined_date = models.DateField(blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default="M")
    address_line1 = models.CharField(max_length=255, blank=False, null=False)
    address_line2 = models.CharField(max_length=255, blank=True, default="")
    address_line3 = models.CharField(max_length=255, blank=True, default="")
    city = models.CharField(max_length=255, blank=False, null=False)
    state = models.CharField(max_length=2, blank=False, null=False)
    country = models.CharField(max_length=2, blank=False, null=False)
    hourly_pay = models.PositiveIntegerField(blank=False, null=False)
    daily_break_minutes = models.PositiveIntegerField(
        blank=False, null=False, default=30
    )
    is_active = models.BooleanField(blank=False, null=False, default=True)
    shift_start_time = models.TimeField(blank=True, null=True)

    @property
    def full_name(self):
        name = self.first_name
        if self.middle_name:
            name = f"{name} {self.middle_name}"
        if self.last_name:
            name = f"{name} {self.last_name}"
        return name

    @property
    def age(self):
        if self.date_of_birth:
            return datetime.datetime.today().year - self.date_of_birth.year

    def get_absolute_url(self):
        return reverse("employee_detail", args=[self.id])

    def __str__(self):
        return self.full_name


class Attendance(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.PROTECT, null=False, blank=False
    )

    date = models.DateField(blank=False, null=False)
    start = models.TimeField(blank=False, null=False)
    end = models.TimeField(blank=True, null=True)
    hourly_pay = models.PositiveIntegerField(blank=False, null=False)
    break_minutes = models.PositiveIntegerField(blank=False, null=False)
    is_deleted = models.BooleanField(default=False)

    @property
    def is_valid(self):
        return (
            True
            if self.date and self.start and self.end and self.start < self.end
            else False
        )

core/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError

from core.models import Department, Employee, Attendance


class EmployeeForm(forms.ModelForm):
    date_of_birth = forms.CharField(widget=forms.TextInput(attrs={"type": "date"}))
    joined_date = forms.CharField(widget=forms.TextInput(attrs={"type": "date"}))
    shift_start_time = forms.CharField(widget=forms.TextInput(attrs={"type": "time"}))

    class Meta:
        model = Employee
        fields = (
            "first_name",
            "middle_name",
            "last_name",
            "phone",
            "email",
            "gender",
            "date_of_birth",
            "address_line1",
            "address_line2",
            "address_line3",
            "city",
            "state",
            "country",
            "department",
            "role",
            "joined_date",
            "hourly_pay",
            "daily_break_minutes",
            "shift_start_time",
        )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        kwargs.setdefault("label_suffix", "")
        super().__init__(*args, **kwargs)
        self.fields["department"] = forms.ModelChoiceField(
            queryset=Department.objects.filter(company=user.company)
        )
        self.fields["shift_start_time"] = forms.CharField(
            widget=forms.TextInput(attrs={"type": "time"}),
            initial=user.company.shift_start_time,
            required=False,
        )
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control form-control-user"


class AttendanceForm(forms.ModelForm):
    class Meta:
        model = Attendance
        fields = "__all__"

    def clean(self):
        cleaned_data = super().clean()
        start = cleaned_data.get("start")
        end = cleaned_data.get("end")
        if start and end and start > end:
            raise ValidationError("Start time cannot be greater than end time.")


class BillingFilterForm(forms.Form):
    MONTH_CHOICES = [
        (1, "January"),
        (2, "February"),
        (3, "March"),
        (4, "April"),
        (5, "May"),
        (6, "June"),
        (7, "July"),
        (8, "August"),
        (9, "September"),
        (10, "October"),
        (11, "November"),
        (12, "December"),
    ]
    month = forms.ChoiceField(
        choices=MONTH_CHOICES, required=True, initial=datetime.date.today().month
    )
    year = forms.IntegerField(
        min_value=2020,
        max_value=datetime.date.today().year,
        required=True,
        initial=datetime.date.today().year,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control form-control-user"

core/views.py
import datetime

import dateutil.parser
import pytz
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.db.models import Q

from core.forms import EmployeeForm, BillingFilterForm
from core.models import Employee, Attendance
from core.utils import str_to_time, str_to_date, get_time_diff, seconds_to_hours_minutes


def test(request):
    return render(request, "attendance/create.html")


@login_required
def dashboard(request):
    return render(request, "dashboard.html")


@login_required
def employee_list(request):
    employees = (
        Employee.objects.filter(
            department__company=request.user.company, is_active=True
        )
        .order_by("-id")
        .all()
    )
    return render(request, "employee/list.html", {"employees": employees})


def get_employee_by_pk(pk, user):
    employee = Employee.objects.filter(pk=pk, is_active=True).first()
    if employee and employee.department.company == user.company:
        return employee
    raise PermissionDenied


@login_required
def employee_detail(request, pk):
    employee = get_employee_by_pk(pk=pk, user=request.user)
    return render(request, "employee/detail.html", {"employee": employee})


class CreateEmployeeView(CreateView):
    model = Employee
    template_name = "employee/create.html"
    form_class = EmployeeForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_success_url(self):
        emp_id = self.kwargs["pk"]
        return reverse_lazy("employee_detail", kwargs={"pk": emp_id})


class UpdateEmployeeView(UpdateView):
    model = Employee
    template_name = "employee/update.html"
    form_class = EmployeeForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def get_success_url(self):
        emp_id = self.kwargs["pk"]
        return reverse_lazy("employee_detail", kwargs={"pk": emp_id})


def is_duplicate_attendance(date, start, end, exclude=None):
    if end:
        return (
            Attendance.objects.filter(
                (Q(start__lte=start) & Q(end__gt=start))
                | (Q(start__lt=end) & Q(end__gte=end))
                | (Q(start__gte=start) & Q(end__lte=end)),
                date=date,
                is_deleted=False,
            )
            .exclude(pk=exclude)
            .exists()
        )
    return Attendance.objects.filter(
        Q(start__lte=start) & Q(end__gt=start),
        date=date,
    ).exists()


@login_required
def attendance(request):
    if request.method == "GET":
        india_tz = pytz.timezone("Asia/Kolkata")
        total_days_till_today = 3
        today = datetime.datetime.now(india_tz).date()
        employees = Employee.objects.filter(
            is_active=True,
            department__company=request.user.company,
        ).all()
        attendances = (
            Attendance.objects.filter(
                date__lte=today,
                date__gte=today - datetime.timedelta(days=total_days_till_today - 1),
                employee__in=employees,
                is_deleted=False,
            )
            .order_by("date", "start")
            .all()
        )
        dates = [
            today - datetime.timedelta(days=days)
            for days in reversed(range(total_days_till_today))
        ]
        data = {}
        for emp in employees:
            data[emp] = {date: [] for date in dates}
        for attn in attendances:
            if attn.date in data[attn.employee]:
                data[attn.employee][attn.date].append(attn)

        return render(request, "attendance/create.html", {"dates": dates, "data": data})

    elif request.method == "POST":
        employee = get_employee_by_pk(pk=request.POST["employee_id"], user=request.user)
        date = str_to_date(request.POST["date"])
        start = str_to_time(request.POST["start"])
        end = str_to_time(request.POST["end"])
        created = False
        if not is_duplicate_attendance(date, start, end):
            Attendance.objects.create(
                employee=employee,
                date=date,
                start=start,
                end=end,
                hourly_pay=int(request.POST["pay"]),
                daily_break_minutes=int(request.POST["break"]),
            )
            created = True
        return get_attendance_by_employee(
            employee=employee,
            date=date,
            message=None
            if created
            else "Attendance is overlapping with existing attendance",
        )


def get_attendance_by_employee(employee, date, message=None):
    attendances = (
        Attendance.objects.filter(date=date, employee=employee, is_deleted=False)
        .order_by("start")
        .all()
    )
    response = {
        "data": [
            {
                "id": attn.id,
                "start": attn.start,
                "end": attn.end,
                "is_valid": attn.is_valid,
                "pay": attn.hourly_pay,
                "break": attn.break_minutes,
            }
            for attn in attendances
        ],
        "message": message,
    }
    return JsonResponse(response)


def get_attendance_or_404(attn_id):
    attn = get_object_or_404(Attendance, pk=attn_id)
    if attn.is_deleted:
        raise Http404("Attendance record not found.")
    return attn


@login_required
def update_attendance(request, attn_id):
    if request.method == "POST":
        attn = get_attendance_or_404(attn_id)
        emp = get_employee_by_pk(attn.employee_id, request.user)
        start = str_to_time(request.POST["start"])
        end = str_to_time(request.POST["end"])
        updated = False
        if not is_duplicate_attendance(attn.date, start, end, exclude=attn.id):
            attn.start = start
            attn.end = end
            attn.hourly_pay = int(request.POST["pay"])
            attn.break_minutes = int(request.POST["break"])
            attn.save()
            updated = True
        return get_attendance_by_employee(
            employee=emp,
            date=attn.date,
            message=None
            if updated
            else "Attendance is overlapping with existing attendance",
        )


@login_required
def delete_attendance(request, attn_id):
    if request.method == "POST":
        attn = get_attendance_or_404(attn_id)
        emp = get_employee_by_pk(attn.employee_id, request.user)
        attn.is_deleted = True
        attn.save()
        return get_attendance_by_employee(employee=emp, date=attn.date)


@login_required
def list_employee_attendances(request, pk):
    emp = get_employee_by_pk(pk=pk, user=request.user)

    date_range = request.GET.get("fromtodate")
    if date_range:
        start, end = date_range.split(",")
        start = dateutil.parser.parse(start).date()
        end = dateutil.parser.parse(end).date()
    else:
        india_tz = pytz.timezone("Asia/Kolkata")
        start = datetime.datetime.now(india_tz).date()
        end = start

    date_map = {
        (end - datetime.timedelta(days=x)): [] for x in range((end - start).days + 1)
    }
    attns = (
        Attendance.objects.filter(
            employee=emp, date__gte=start, date__lte=end, is_deleted=False
        )
        .order_by("date", "start")
        .all()
    )
    for attn in attns:
        if attn.date in date_map:
            date_map[attn.date].append(attn)
    return render(
        request,
        "attendance/employee_attendance.html",
        {"data": date_map, "employee": emp, "start": start, "end": end},
    )


@login_required
def view_employee_billing(request, pk):
    emp = get_employee_by_pk(pk=pk, user=request.user)
    month = request.GET.get("month")
    year = request.GET.get("year")
    if not (month and year):
        month = datetime.date.today().month
        year = datetime.date.today().year

    attns = Attendance.objects.filter(
        employee=emp,
        date__year=year,
        date__month=month,
        is_deleted=False,
    ).all()

    data = {
        "cost": 0,
        "work": (0, 0),
    }
    ceiling_minutes = request.user.company.ceiling_minutes
    for attn in attns:
        if not attn.is_valid:
            continue

        work_seconds = get_time_diff(start=attn.start, end=attn.end)
        break_seconds = attn.break_minutes * 60
        effective_seconds = max(work_seconds - break_seconds, 0)
        hours, minutes = seconds_to_hours_minutes(effective_seconds)
        if (minutes + ceiling_minutes) >= 60:
            hours += 1
            minutes = 0
        hours_in_decimal = hours + (minutes / 60)
        cost = hours_in_decimal * attn.hourly_pay

        data["work"] = (data["work"][0] + hours, data["work"][1] + minutes)
        data["cost"] += cost

    data["cost"] = round(data["cost"])
    data["work"] = (data["work"][0] + (data["work"][1] // 60), data["work"][1] % 60)
    data["work"] = f"{data['work'][0]} hours and {data['work'][1]} minutes"

    return render(
        request,
        "billing/employee_billing.html",
        {
            "data": data,
            "employee": emp,
            "form": BillingFilterForm(initial={"month": int(month), "year": int(year)}),
        },
    )

core/templates/employee/create.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add Employee</h1>
        </div>
    </div>
    <div class="container-fluid">
        {% include "employee/employee_form.html" with btn_name="Create" %}
    </div>

{% endblock %}

core/templates/employee/list.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Employees</h1>
            <a href="{% url 'employee_create' %}"
               class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                    class="fas fa-download fa-sm text-white-50"></i> &nbsp Add
                Employee</a>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row row-cols-md-3 row-cols-sm-1">
            <div class="col">
                <div class="form-group">
                    <label for="id_search">Search</label>
                    <input type="text" name="search"
                           class="form-control form-control-user"
                           id="id_search">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="id_role">Role</label>
                    <select name="role" class="form-control form-control-user"
                            id="id_role">
                        <option value="All" selected>All</option>
                    </select>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="id_department">Department</label>
                    <select name="department" class="form-control form-control-user"
                            id="id_department">
                        <option value="All" selected>All</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%"
                           cellspacing="0">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Role</th>
                            <th>Department</th>
                            <th>Age</th>
                            <th>Gender</th>
                            <th>Joined date</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Role</th>
                            <th>Department</th>
                            <th>Age</th>
                            <th>Gender</th>
                            <th>Joined date</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for obj in employees %}
                            <tr>
                                <td>
                                    <a href="{% url 'employee_detail' pk=obj.id %}">
                                        {{ obj.full_name|default:"" }}
                                    </a>
                                </td>
                                <td>{{ obj.phone|default:"" }}</td>
                                <td>{{ obj.role|default:"" }}</td>
                                <td>{{ obj.department|default:"" }}</td>
                                <td>{{ obj.age|default:"" }}</td>
                                <td>{{ obj.gender|default:"" }}</td>
                                <td>{{ obj.joined_date|default:"" }}</td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        let map_choice = function (column, id_select) {
            let select = $('#' + id_select).on('change', function () {
                let search_val = $(this).val()
                if (search_val === 'All') {
                    column.search('^.*$', true, false).draw();
                } else {
                    var val = $.fn.dataTable.util.escapeRegex(search_val);
                    column.search(val ? '^' + val + '$' : '', true, false).draw();
                }
            })
            column
                .data()
                .unique()
                .sort()
                .each(function (d, j) {
                    select.append('<option value="' + d + '">' + d + '</option>');
                });
        }
        $(document).ready(function () {
            let table = $('#dataTable').DataTable({
                paging: true,
                ordering: true,
                info: false,
                searching: true,
                order: [],
                drawCallback: function (settings) {
                    var pagination = $(this).closest('.dataTables_wrapper').find('.dataTables_paginate');
                    pagination.toggle(this.api().page.info().pages > 1);
                },
                initComplete: function () {
                    map_choice(this.api().column(2), 'id_role');
                    map_choice(this.api().column(3), 'id_department');
                },
                dom: 'lrt',
            });
            $('#id_search').on('keyup', function () {
                table.search(this.value).draw();
            });
        })
    </script>
{% endblock %}

core/templates/employee/update.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Update Employee</h1>
            <a href="{% url 'employee_detail' pk=object.id %}"
                   class="d-none d-sm-inline-block btn btn btn-primary shadow-sm m-2"><i
                        class="fas fa-user fa-sm text-white-100"></i>&nbsp
                    Employee</a>
        </div>
    </div>
    <div class="container-fluid">
        {% include "employee/employee_form.html" with btn_name="Update" %}
    </div>
    <div class="container-fluid"><br></div>

{% endblock %}